on: push
jobs:
    second-job:
        runs-on: windows-latest, macos-latest, ubuntu-latest
        steps:
            - run: node --version
            - run: npm --version
            - uses: action/checkout@v3
            - run: node index.jsgit a